pipeline {
    agent{
        docker{
            image 'snakee/golang-junit:1.21'
            reuseNode true
        }
    }

    stages {
        stage('Unit Test - Backend') {
            steps {
                dir('bugtracker-backend'){
                    sh '''
                        export GOCACHE=/var/jenkins_home/.cache/go-build
                        mkdir -p $GOCACHE
                        go test -v ./...
                        '''
                }
            }
        }
    }
}
