pipeline {
    agent {
        docker {
            image 'snakee/golang-junit:1.21'
            reuseNode true
            args '-u root'
        }
    }

    stages {
        stage('Unit Test - Backend') {
            steps {
                dir('bugtracker-backend') {
                    sh '''
                        go test -v ./...
                    '''
                }
            }
        }
    }
}